DROP TABLE IF EXISTS book_authors;

DROP TABLE IF EXISTS book_purchases;

DROP TABLE IF EXISTS books;

DROP TABLE IF EXISTS publishers;

DROP TABLE IF EXISTS authors;

--
-- 制約などを追加した例
--
CREATE TABLE authors (
  author_id INTEGER PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  country_code CHAR(2) CHECK (country_code IN ('JP', 'US', 'FR')), -- ★
  birthday DATE
);

CREATE TABLE publishers (
  publisher_id INTEGER PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  zip_code CHAR(8) NOT NULL CHECK (zip_code ~ '^[0-9]{3}-[0-9]{4}$') -- ★
);

CREATE TABLE books (
  book_id INTEGER PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  price INTEGER NOT NULL CHECK (price >= 0), -- ★
  print_run INTEGER CHECK (print_run > 0), -- ★
  release_date DATE, -- 発売日
  publisher_id INTEGER REFERENCES publishers (publisher_id) ON DELETE SET NULL -- ★
);

CREATE TABLE book_authors (
  book_id INTEGER REFERENCES books (book_id), -- ★
  author_id INTEGER REFERENCES authors (author_id), -- ★
  PRIMARY KEY (book_id, author_id), -- ★
  author_order INTEGER NOT NULL, -- 著者順序
  UNIQUE (book_id, author_order) -- ★
);

CREATE TABLE book_purchases (
  -- id SERIAL PRIMARY KEY,
  -- id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, -- ★
  -- id INTEGER GENERATED ALWAYS AS IDENTITY (
  --   START
  --   WITH
  --     1
  -- ) PRIMARY KEY, -- ★
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ★
  book_id INTEGER REFERENCES books (book_id), -- ★
  qty INTEGER NOT NULL CHECK (qty > 0), -- ★
  -- purchased_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP(0) -- ★
  -- purchased_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(0) -- ★
  purchased_at TIMESTAMP DEFAULT DATE_TRUNC('second', CURRENT_TIMESTAMP) NOT NULL -- ★
);